version: '3'

services: 
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      MYSQL_URI: mysql+mysqlconnector://weather:weather-password@mysql-db:3306/weather-app
    volumes:
      - ./app:/server/app:ro
    depends_on:
      - mysql-db
    ports:
      - 8000:8000

  mysql-db:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_DATABASE: weather-app
      MYSQL_USER: weather
      MYSQL_PASSWORD: weather-password
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - mysql-db-data:/var/lib/mysql
    ports:
      - 3306:3306

volumes:
  mysql-db-data:
